### PR TITLE
Bump to citus_enterprise 10.2.0-2

### PR DESCRIPTION
**Pull request by gurkanindibay**

### CODE REVIEW

**Comment by hanefi** [comment]
@gurkanindibay you need to supply a new section in 2 places
- debian/changelog
- citus-enterprise.spec

You also need to update `Release` field in the spec file

**Comment by hanefi** [comment]
Please update the PR description as well. This is no regular version bump

**Comment by gurkanindibay** [comment]
> @gurkanindibay you need to supply a new section in 2 places
> 
> * debian/changelog
> * citus-enterprise.spec
> 
> You also need to update `Release` field in the spec file

Fixed

**Comment by gurkanindibay** [comment]
> Please update the PR description as well. This is no regular version bump

Fixed

**Review by hanefi — DISMISSED** [review]

**Review by hanefi — APPROVED** [review]

**Pull request merged**
