### PR TITLE
Bump pg_auto_failover enterprise version to 1.3.2

### PR DESCRIPTION
**Pull request by onurctirtir**

### CODE REVIEW

**Review by DimCitus — APPROVED** [review]

**Comment by hanefi** [comment]
Interesting error on ubuntu Xenial build https://travis-ci.org/github/citusdata/packaging/jobs/745380240
```
E: pg-auto-failover-cli-enterprise-1.3: versioned-provides pg-auto-failover-cli-enterprise (= 1.3.2-1)
```

**Comment by DimCitus** [comment]
> Interesting error on ubuntu Xenial build https://travis-ci.org/github/citusdata/packaging/jobs/745380240
> 
> ```
> E: pg-auto-failover-cli-enterprise-1.3: versioned-provides pg-auto-failover-cli-enterprise (= 1.3.2-1)
> ```

Given https://lintian.debian.org/tags/invalid-versioned-provides.html ; yeah, “interesting”.

**Comment by onurctirtir** [comment]
I see that we use the proper operator, so couldn't understand why we have this error message
https://github.com/citusdata/packaging/blob/all-pgautofailover-enterprise/debian/control.in#L13

**Comment by DimCitus** [comment]
Could it be because we include the debian version number in our version number? Is it possible to try with `(= 1.3.2)`, that is only with the package version number, without the debian package revision?

**Comment by onurctirtir** [comment]
> Could it be because we include the debian version number in our version number? Is it possible to try with `(= 1.3.2)`, that is only with the package version number, without the debian package revision?

Yeah, it could be related with `-` version, but as I talked with @JelteF, it doesn't seem to be a problem, it's there for a while for some old debian based distros.

So, now are we good to merge @DimCitus , @hanefi  ?

**Review by hanefi — APPROVED** [review]
LGTM
:shipit:

**Comment by DimCitus** [comment]
If you could install the resulting package without trouble, then I'm good. We need to make sure the Lintian check won't activate and prevent installation of the package on the users/customer systems.

**Comment by JelteF** [comment]
For context it's not `invalid-versioned-provides`, but the now removed `versioned-provides`.
Error description: http://people.ubuntuwire.org/~broder/lintian/quantal/tags/versioned-provides.html
Removal of the lint: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800438

**Pull request merged**
