### PR TITLE
Bump Citus version to 9.5.1

### PR DESCRIPTION
**Pull request by onurctirtir**

### CODE REVIEW

**Review by hanefi — APPROVED** [review]
:shipit:

**Comment by hanefi** [comment]
The outputs for community seems ok, however the enterprise outputs indicate that there might be some issues with debian changelog.

See warning messages at https://travis-ci.com/github/citusdata/packaging/jobs/452583016

```
W: postgresql-11-citus-enterprise-9.5: syntax-error-in-debian-changelog line 13 "badly formatted trailer line"
W: postgresql-11-citus-enterprise-9.5: syntax-error-in-debian-changelog line 15 "found start of entry where expected more change data or trailer"
W: postgresql-11-citus-enterprise-9.5: debian-changelog-line-too-long line 5
```

**Comment by onurctirtir** [comment]
> The outputs for community seems ok, however the enterprise outputs indicate that there might be some issues with debian changelog.
> 
> See warning messages at https://travis-ci.com/github/citusdata/packaging/jobs/452583016
> 
> ```
> W: postgresql-11-citus-enterprise-9.5: syntax-error-in-debian-changelog line 13 "badly formatted trailer line"
> W: postgresql-11-citus-enterprise-9.5: syntax-error-in-debian-changelog line 15 "found start of entry where expected more change data or trailer"
> W: postgresql-11-citus-enterprise-9.5: debian-changelog-line-too-long line 5
> ```

See https://github.com/citusdata/packaging/pull/570#discussion_r535032180

**Comment by onurctirtir** [comment]
Closes https://github.com/citusdata/packaging/pull/558

**Pull request merged**
