### PR TITLE
Bump RedHat TopN to 2.4.0

### LINKED ISSUE #761: Fix TopN RedHat warnings
The date is bogus in rpm changelog for 2.2.2 release
```
warning: bogus date in %changelog: Thu Dec 21 2018 - Furkan Sahin <furkan@citusdata.com> 2.2.2.citus-1 
```

Some migration files are empty
```
topn_11.x86_64: E: zero-length /usr/pgsql-11/share/extension/topn--2.1.0--2.2.0.sql
topn_11.x86_64: E: zero-length /usr/pgsql-11/share/extension/topn--2.2.0--2.2.1.sql
topn_11.x86_64: E: zero-length /usr/pgsql-11/share/extension/topn--2.2.1--2.2.2.sql
topn_11.x86_64: E: zero-length /usr/pgsql-11/share/extension/topn--2.2.2--2.3.0.sql
topn_11.x86_64: E: zero-length /usr/pgsql-11/share/extension/topn--2.3.1--2.4.0.sql
```

Debug Source packages are missing documentation
```
topn_11-debugsource.x86_64: W: no-documentation
```

_Originally posted by @gurkanindibay in https://github.com/citusdata/packaging/pull/760#issuecomment-918896939_

### PR DESCRIPTION
**Pull request by hanefi**

### CODE REVIEW

**Comment by gurkanindibay** [comment]
I see some problematic warnings. It's better to fix them
warning: bogus date in %changelog: Thu Dec 21 2018 - Furkan Sahin <furkan@citusdata.com> 2.2.2.citus-1 
topn_11.x86_64: E: zero-length /usr/pgsql-11/share/extension/topn--2.2.2--2.3.0.sql
error: Package check "/usr/bin/rpmlint -f /rpmlintrc /citus-rpm-build/x86_64/topn_14-2.4.0.citus-1.el7.x86_64.rpm" failed.
These are nor super urgent since some of them are very old but I think an issue can be opened

**Comment by hanefi** [comment]
> I see some problematic warnings. It's better to fix them
> warning: bogus date in %changelog: Thu Dec 21 2018 - Furkan Sahin [furkan@citusdata.com](mailto:furkan@citusdata.com) 2.2.2.citus-1
> topn_11.x86_64: E: zero-length /usr/pgsql-11/share/extension/topn--2.2.2--2.3.0.sql
> error: Package check "/usr/bin/rpmlint -f /rpmlintrc /citus-rpm-build/x86_64/topn_14-2.4.0.citus-1.el7.x86_64.rpm" failed.
> These are nor super urgent since some of them are very old but I think an issue can be opened

I created an issue and added one more warning message in there as well.

I think we can go ahead and move forward, as these 2 warnings you shared should actually be fixed in the project repo, not here.

**Review by onurctirtir — APPROVED** [review]

**Review by gurkanindibay — COMMENTED** [review]
LGTM after issue. Please link issue to this PR

**Review by gurkanindibay — APPROVED** [review]
LGTM after issue. Please link issue to be able to track the reason we open issue

**Pull request merged**
